/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaz;

import Clases.Canasta;
import Clases.Fruta;
import javax.swing.JOptionPane;

/**
 *
 * @author celia
 */
public class JDCatalogo extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDCatalogo.class.getName());
    
    Canasta miCanasta = new Canasta();
    /**
     * Creates new form JDCatalogo
     */
    public JDCatalogo(java.awt.Frame parent, boolean modal, Canasta canastaRecibida) {
        super(parent, modal);
        initComponents();
        this.miCanasta = canastaRecibida;
        setLocationRelativeTo(null);
        setTitle("Catálogo");
    }
    private Fruta buscarEnInventario(String nombre) {
    switch (nombre.toLowerCase()) {
        case "manzana": return new Fruta(1, "Manzana", 45.00);
        case "mango": return new Fruta(2, "Mango", 35.50);
         case "kiwi": return new Fruta(3, "Kiwi", 80.00);
        case "fresa": return new Fruta(4, "Fresa", 65.00);
        case "banana": return new Fruta(5, "Banana", 22.00);
        case "pera": return new Fruta(6, "Pera", 38.00);
        case "naranja": return new Fruta(7, "Naranja", 18.00);
        case "sandia": return new Fruta(8, "Sandia", 15.00);
        case "durazno": return new Fruta(9, "Durazno", 55.00);
        case "uvas": return new Fruta(10, "Uvas", 70.00);
        case "limon": return new Fruta(11, "Limon", 25.00);
        case "aguacate": return new Fruta(12, "Aguacate", 90.00);
        default: return null;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        JManzana = new javax.swing.JButton();
        JMango = new javax.swing.JButton();
        JKiwi = new javax.swing.JButton();
        JFresa = new javax.swing.JButton();
        JSandia = new javax.swing.JButton();
        JNaranja = new javax.swing.JButton();
        JPera = new javax.swing.JButton();
        JBanana = new javax.swing.JButton();
        JDurazno = new javax.swing.JButton();
        JUvas = new javax.swing.JButton();
        JLimon = new javax.swing.JButton();
        JAguacate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JBuscarFruta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Catalogo de frutas ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Manzana");

        jLabel4.setText("Mango");

        jLabel5.setText("Kiwi");

        jLabel6.setText("Fresa");

        jLabel7.setText("$45.00");

        jLabel8.setText("$35.50");

        jLabel9.setText("$80.00");

        jLabel10.setText("$65.00");

        jLabel11.setText("Banana");

        jLabel12.setText("Pera");

        jLabel13.setText("Naranja");

        jLabel14.setText("Sandia");

        jLabel15.setText("$15.00");

        jLabel16.setText("$38.00");

        jLabel17.setText("$18.00");

        jLabel18.setText("$22.00");

        jLabel19.setText("Durazno");

        jLabel20.setText("Uvas");

        jLabel21.setText("Limon");

        jLabel22.setText("Aguacate");

        jLabel23.setText("$90.00");

        jLabel24.setText("$25.00");

        jLabel25.setText("$70.00");

        jLabel26.setText("$55.00");

        JManzana.setText("Comprar");
        JManzana.addActionListener(this::JManzanaActionPerformed);

        JMango.setText("Comprar");
        JMango.addActionListener(this::JMangoActionPerformed);

        JKiwi.setText("Comprar");
        JKiwi.addActionListener(this::JKiwiActionPerformed);

        JFresa.setText("Comprar");
        JFresa.addActionListener(this::JFresaActionPerformed);

        JSandia.setText("Comprar");
        JSandia.addActionListener(this::JSandiaActionPerformed);

        JNaranja.setText("Comprar");
        JNaranja.addActionListener(this::JNaranjaActionPerformed);

        JPera.setText("Comprar");
        JPera.addActionListener(this::JPeraActionPerformed);

        JBanana.setText("Comprar");
        JBanana.addActionListener(this::JBananaActionPerformed);

        JDurazno.setText("Comprar");
        JDurazno.addActionListener(this::JDuraznoActionPerformed);

        JUvas.setText("Comprar");
        JUvas.addActionListener(this::JUvasActionPerformed);

        JLimon.setText("Comprar");
        JLimon.addActionListener(this::JLimonActionPerformed);

        JAguacate.setText("Comprar");
        JAguacate.addActionListener(this::JAguacateActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel26)))
                    .addComponent(jLabel7))
                .addGap(116, 116, 116)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20)
                    .addComponent(jLabel25)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(jLabel24)
                    .addComponent(jLabel9))
                .addGap(115, 115, 115)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel6))
                .addGap(61, 61, 61))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JManzana)
                    .addComponent(JBanana)
                    .addComponent(JDurazno))
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JMango)
                    .addComponent(JPera)
                    .addComponent(JUvas))
                .addGap(96, 96, 96)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JLimon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(JAguacate))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(JNaranja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JSandia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(JKiwi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JFresa)))
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JMango, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JKiwi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFresa, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JSandia, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPera, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBanana, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JDurazno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JUvas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLimon, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JAguacate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel2.setText("Buscar fruta:");

        JBuscarFruta.addActionListener(this::JBuscarFrutaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBuscarFruta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JBuscarFruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(515, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBuscarFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBuscarFrutaActionPerformed
        String nombreBuscado = JBuscarFruta.getText().trim();
    Fruta encontrada = buscarEnInventario(nombreBuscado);

    if (encontrada != null) {
        miCanasta.agregarFruta(encontrada);
        JOptionPane.showMessageDialog(this, encontrada.getNombre() + " comprada y agregada a la canasta");
        JBuscarFruta.setText(""); // Limpia el buscador después de comprar
    } else {
        JOptionPane.showMessageDialog(this, "La fruta '" + nombreBuscado + "' no existe en nuestro catálogo", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_JBuscarFrutaActionPerformed

    private void JManzanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JManzanaActionPerformed
        miCanasta.agregarFruta(new Fruta(1, "Manzana", 45.00));
        JOptionPane.showMessageDialog(this, "Manzana agregada a la canasta");
    }//GEN-LAST:event_JManzanaActionPerformed

    private void JFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFresaActionPerformed
        miCanasta.agregarFruta(new Fruta(4, "Fresa", 65.00));
        JOptionPane.showMessageDialog(this, "Fresa agregada a la canasta");
    }//GEN-LAST:event_JFresaActionPerformed

    private void JMangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMangoActionPerformed
        miCanasta.agregarFruta(new Fruta(2, "Mango", 35.50));
        JOptionPane.showMessageDialog(this, "Mango agregada a la canasta");
    }//GEN-LAST:event_JMangoActionPerformed

    private void JKiwiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKiwiActionPerformed
        miCanasta.agregarFruta(new Fruta(3, "Kiwi", 80.00));
        JOptionPane.showMessageDialog(this, "Kiwi agregada a la canasta");
    }//GEN-LAST:event_JKiwiActionPerformed

    private void JBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBananaActionPerformed
        miCanasta.agregarFruta(new Fruta(5, "Banana", 22.00));
        JOptionPane.showMessageDialog(this, "Banana agregada a la canasta");
    }//GEN-LAST:event_JBananaActionPerformed

    private void JPeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPeraActionPerformed
        miCanasta.agregarFruta(new Fruta(6, "Pera", 38.00));
        JOptionPane.showMessageDialog(this, "Pera agregada a la canasta");
    }//GEN-LAST:event_JPeraActionPerformed

    private void JNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNaranjaActionPerformed
        miCanasta.agregarFruta(new Fruta(7, "Naranja", 18.00));
        JOptionPane.showMessageDialog(this, "Naranja agregada a la canasta");
    }//GEN-LAST:event_JNaranjaActionPerformed

    private void JSandiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSandiaActionPerformed
        miCanasta.agregarFruta(new Fruta(8, "Sandia", 15.00));
        JOptionPane.showMessageDialog(this, "Sandia agregada a la canasta");
    }//GEN-LAST:event_JSandiaActionPerformed

    private void JDuraznoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDuraznoActionPerformed
        miCanasta.agregarFruta(new Fruta(9, "Durazno", 55.00));
        JOptionPane.showMessageDialog(this, "Durazno agregada a la canasta");
    }//GEN-LAST:event_JDuraznoActionPerformed

    private void JUvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUvasActionPerformed
        miCanasta.agregarFruta(new Fruta(10, "Uvas", 70.00));
        JOptionPane.showMessageDialog(this, "Uvas agregada a la canasta");
    }//GEN-LAST:event_JUvasActionPerformed

    private void JLimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLimonActionPerformed
        miCanasta.agregarFruta(new Fruta(11, "Limon", 25.00));
        JOptionPane.showMessageDialog(this, "Limon agregada a la canasta");
    }//GEN-LAST:event_JLimonActionPerformed

    private void JAguacateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAguacateActionPerformed
        miCanasta.agregarFruta(new Fruta(12, "Aguacate", 90.00));
        JOptionPane.showMessageDialog(this, "Aguacate agregada a la canasta");
    }//GEN-LAST:event_JAguacateActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAguacate;
    private javax.swing.JButton JBanana;
    private javax.swing.JTextField JBuscarFruta;
    private javax.swing.JButton JDurazno;
    private javax.swing.JButton JFresa;
    private javax.swing.JButton JKiwi;
    private javax.swing.JButton JLimon;
    private javax.swing.JButton JMango;
    private javax.swing.JButton JManzana;
    private javax.swing.JButton JNaranja;
    private javax.swing.JButton JPera;
    private javax.swing.JButton JSandia;
    private javax.swing.JButton JUvas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
