/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaz;

import Clases.Canasta;
import Clases.Fruta;
import javax.swing.JOptionPane;

/**
 *
 * @author celia
 */
public class JDCatalogo extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDCatalogo.class.getName());
    
    Canasta miCanasta = new Canasta();
    /**
     * Creates new form JDCatalogo
     */
    public JDCatalogo(java.awt.Frame parent, boolean modal, Canasta canastaRecibida) {
        super(parent, modal);
        initComponents();
        this.miCanasta = canastaRecibida;
        setLocationRelativeTo(null);
        setTitle("Catálogo");
    }
    private Fruta buscarEnInventario(String nombre) {
    switch (nombre.toLowerCase()) {
        case "manzana": return new Fruta(1, "Manzana", 45.00);
        case "mango": return new Fruta(2, "Mango", 35.50);
         case "kiwi": return new Fruta(3, "Kiwi", 80.00);
        case "fresa": return new Fruta(4, "Fresa", 65.00);
        case "banana": return new Fruta(5, "Banana", 22.00);
        case "pera": return new Fruta(6, "Pera", 38.00);
        case "naranja": return new Fruta(7, "Naranja", 18.00);
        case "sandia": return new Fruta(8, "Sandia", 15.00);
        case "durazno": return new Fruta(9, "Durazno", 55.00);
        case "uvas": return new Fruta(10, "Uvas", 70.00);
        case "limon": return new Fruta(11, "Limon", 25.00);
        case "aguacate": return new Fruta(12, "Aguacate", 90.00);
        default: return null;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        JManzana = new javax.swing.JButton();
        JMango = new javax.swing.JButton();
        JKiwi = new javax.swing.JButton();
        JFresa = new javax.swing.JButton();
        JSandia = new javax.swing.JButton();
        JNaranja = new javax.swing.JButton();
        JPera = new javax.swing.JButton();
        JBanana = new javax.swing.JButton();
        JDurazno = new javax.swing.JButton();
        JUvas = new javax.swing.JButton();
        JLimon = new javax.swing.JButton();
        JAguacate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JBuscarFruta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 239, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Yet R", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 102));
        jLabel1.setText("Catalogo de frutas ");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Iconos/Logo_1.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel27))
                .addGap(25, 25, 25))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/manzanaX.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/mangoX.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/kiwiX.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/fresaX.png"))); // NOI18N

        jLabel7.setText("$45.00");

        jLabel8.setText("$35.50");

        jLabel9.setText("$80.00");

        jLabel10.setText("$65.00");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/bananaX.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/peraX.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/naranjaX.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/sandiaX.png"))); // NOI18N

        jLabel15.setText("$15.00");

        jLabel16.setText("$38.00");

        jLabel17.setText("$18.00");

        jLabel18.setText("$22.00");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/duraznoX.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/uvasX.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/limonX.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/productos/aguacateX.png"))); // NOI18N

        jLabel23.setText("$90.00");

        jLabel24.setText("$25.00");

        jLabel25.setText("$70.00");

        jLabel26.setText("$55.00");

        JManzana.setText("Comprar");
        JManzana.addActionListener(this::JManzanaActionPerformed);

        JMango.setText("Comprar");
        JMango.addActionListener(this::JMangoActionPerformed);

        JKiwi.setText("Comprar");
        JKiwi.addActionListener(this::JKiwiActionPerformed);

        JFresa.setText("Comprar");
        JFresa.addActionListener(this::JFresaActionPerformed);

        JSandia.setText("Comprar");
        JSandia.addActionListener(this::JSandiaActionPerformed);

        JNaranja.setText("Comprar");
        JNaranja.addActionListener(this::JNaranjaActionPerformed);

        JPera.setText("Comprar");
        JPera.addActionListener(this::JPeraActionPerformed);

        JBanana.setText("Comprar");
        JBanana.addActionListener(this::JBananaActionPerformed);

        JDurazno.setText("Comprar");
        JDurazno.addActionListener(this::JDuraznoActionPerformed);

        JUvas.setText("Comprar");
        JUvas.addActionListener(this::JUvasActionPerformed);

        JLimon.setText("Comprar");
        JLimon.addActionListener(this::JLimonActionPerformed);

        JAguacate.setText("Comprar");
        JAguacate.addActionListener(this::JAguacateActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JManzana)
                                .addComponent(JBanana))
                            .addComponent(jLabel19)
                            .addComponent(JDurazno))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JMango)
                                    .addComponent(JPera)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel16)))
                                .addGap(96, 265, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(92, 92, 92))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(JUvas))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel10)
                                .addGap(96, 96, 96))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(128, 128, 128)
                                                .addComponent(jLabel8))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(186, 186, 186)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel17)))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JKiwi)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel21)
                                            .addComponent(JNaranja)
                                            .addComponent(JLimon))
                                        .addGap(4, 4, 4)))))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel26)
                        .addGap(121, 121, 121)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addGap(89, 89, 89)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(JFresa)
                            .addComponent(JSandia)
                            .addComponent(jLabel22)
                            .addComponent(JAguacate))
                        .addGap(71, 71, 71))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(97, 97, 97))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JManzana, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JMango, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JKiwi, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JFresa, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JPera, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBanana, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JNaranja, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JSandia, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)))
                        .addGap(11, 11, 11)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JUvas, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JDurazno, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JAguacate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLimon, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Buscar fruta:");

        JBuscarFruta.setBackground(new java.awt.Color(204, 255, 204));
        JBuscarFruta.addActionListener(this::JBuscarFrutaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBuscarFruta, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBuscarFruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBuscarFrutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBuscarFrutaActionPerformed
        String nombreBuscado = JBuscarFruta.getText().trim();
    Fruta encontrada = buscarEnInventario(nombreBuscado);

    if (encontrada != null) {
        miCanasta.agregarFruta(encontrada);
        JOptionPane.showMessageDialog(this, encontrada.getNombre() + " comprada y agregada a la canasta");
        JBuscarFruta.setText(""); // Limpia el buscador después de comprar
    } else {
        JOptionPane.showMessageDialog(this, "La fruta '" + nombreBuscado + "' no existe en nuestro catálogo", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_JBuscarFrutaActionPerformed

    private void JManzanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JManzanaActionPerformed
        miCanasta.agregarFruta(new Fruta(1, "Manzana", 45.00));
        JOptionPane.showMessageDialog(this, "Manzana agregada a la canasta");
    }//GEN-LAST:event_JManzanaActionPerformed

    private void JFresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFresaActionPerformed
        miCanasta.agregarFruta(new Fruta(4, "Fresa", 65.00));
        JOptionPane.showMessageDialog(this, "Fresa agregada a la canasta");
    }//GEN-LAST:event_JFresaActionPerformed

    private void JMangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMangoActionPerformed
        miCanasta.agregarFruta(new Fruta(2, "Mango", 35.50));
        JOptionPane.showMessageDialog(this, "Mango agregada a la canasta");
    }//GEN-LAST:event_JMangoActionPerformed

    private void JKiwiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JKiwiActionPerformed
        miCanasta.agregarFruta(new Fruta(3, "Kiwi", 80.00));
        JOptionPane.showMessageDialog(this, "Kiwi agregada a la canasta");
    }//GEN-LAST:event_JKiwiActionPerformed

    private void JBananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBananaActionPerformed
        miCanasta.agregarFruta(new Fruta(5, "Banana", 22.00));
        JOptionPane.showMessageDialog(this, "Banana agregada a la canasta");
    }//GEN-LAST:event_JBananaActionPerformed

    private void JPeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPeraActionPerformed
        miCanasta.agregarFruta(new Fruta(6, "Pera", 38.00));
        JOptionPane.showMessageDialog(this, "Pera agregada a la canasta");
    }//GEN-LAST:event_JPeraActionPerformed

    private void JNaranjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNaranjaActionPerformed
        miCanasta.agregarFruta(new Fruta(7, "Naranja", 18.00));
        JOptionPane.showMessageDialog(this, "Naranja agregada a la canasta");
    }//GEN-LAST:event_JNaranjaActionPerformed

    private void JSandiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSandiaActionPerformed
        miCanasta.agregarFruta(new Fruta(8, "Sandia", 15.00));
        JOptionPane.showMessageDialog(this, "Sandia agregada a la canasta");
    }//GEN-LAST:event_JSandiaActionPerformed

    private void JDuraznoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JDuraznoActionPerformed
        miCanasta.agregarFruta(new Fruta(9, "Durazno", 55.00));
        JOptionPane.showMessageDialog(this, "Durazno agregada a la canasta");
    }//GEN-LAST:event_JDuraznoActionPerformed

    private void JUvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUvasActionPerformed
        miCanasta.agregarFruta(new Fruta(10, "Uvas", 70.00));
        JOptionPane.showMessageDialog(this, "Uvas agregada a la canasta");
    }//GEN-LAST:event_JUvasActionPerformed

    private void JLimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLimonActionPerformed
        miCanasta.agregarFruta(new Fruta(11, "Limon", 25.00));
        JOptionPane.showMessageDialog(this, "Limon agregada a la canasta");
    }//GEN-LAST:event_JLimonActionPerformed

    private void JAguacateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAguacateActionPerformed
        miCanasta.agregarFruta(new Fruta(12, "Aguacate", 90.00));
        JOptionPane.showMessageDialog(this, "Aguacate agregada a la canasta");
    }//GEN-LAST:event_JAguacateActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JAguacate;
    private javax.swing.JButton JBanana;
    private javax.swing.JTextField JBuscarFruta;
    private javax.swing.JButton JDurazno;
    private javax.swing.JButton JFresa;
    private javax.swing.JButton JKiwi;
    private javax.swing.JButton JLimon;
    private javax.swing.JButton JMango;
    private javax.swing.JButton JManzana;
    private javax.swing.JButton JNaranja;
    private javax.swing.JButton JPera;
    private javax.swing.JButton JSandia;
    private javax.swing.JButton JUvas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
